// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Account       string
	Deposit       string
	Promotion     string
	PromotionTask string
	Reward        string
	Withdrawal    string
}{
	Account:       "account",
	Deposit:       "deposit",
	Promotion:     "promotion",
	PromotionTask: "promotion_task",
	Reward:        "reward",
	Withdrawal:    "withdrawal",
}
