// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testDeposits(t *testing.T) {
	t.Parallel()

	query := Deposits()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testDepositsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Deposit{}
	if err = randomize.Struct(seed, o, depositDBTypes, true, depositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Deposits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDepositsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Deposit{}
	if err = randomize.Struct(seed, o, depositDBTypes, true, depositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Deposits().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Deposits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDepositsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Deposit{}
	if err = randomize.Struct(seed, o, depositDBTypes, true, depositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DepositSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Deposits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testDepositsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Deposit{}
	if err = randomize.Struct(seed, o, depositDBTypes, true, depositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := DepositExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Deposit exists: %s", err)
	}
	if !e {
		t.Errorf("Expected DepositExists to return true, but got false.")
	}
}

func testDepositsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Deposit{}
	if err = randomize.Struct(seed, o, depositDBTypes, true, depositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	depositFound, err := FindDeposit(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if depositFound == nil {
		t.Error("want a record, got nil")
	}
}

func testDepositsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Deposit{}
	if err = randomize.Struct(seed, o, depositDBTypes, true, depositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Deposits().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testDepositsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Deposit{}
	if err = randomize.Struct(seed, o, depositDBTypes, true, depositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Deposits().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testDepositsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	depositOne := &Deposit{}
	depositTwo := &Deposit{}
	if err = randomize.Struct(seed, depositOne, depositDBTypes, false, depositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}
	if err = randomize.Struct(seed, depositTwo, depositDBTypes, false, depositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = depositOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = depositTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Deposits().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testDepositsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	depositOne := &Deposit{}
	depositTwo := &Deposit{}
	if err = randomize.Struct(seed, depositOne, depositDBTypes, false, depositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}
	if err = randomize.Struct(seed, depositTwo, depositDBTypes, false, depositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = depositOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = depositTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Deposits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testDepositsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Deposit{}
	if err = randomize.Struct(seed, o, depositDBTypes, true, depositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Deposits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDepositsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Deposit{}
	if err = randomize.Struct(seed, o, depositDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(depositColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Deposits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testDepositToOneAccountUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Deposit
	var foreign Account

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, depositDBTypes, false, depositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, accountDBTypes, false, accountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Account struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := DepositSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*Deposit)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testDepositToOneSetOpAccountUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Deposit
	var b, c Account

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, depositDBTypes, false, strmangle.SetComplement(depositPrimaryKeyColumns, depositColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, accountDBTypes, false, strmangle.SetComplement(accountPrimaryKeyColumns, accountColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, accountDBTypes, false, strmangle.SetComplement(accountPrimaryKeyColumns, accountColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Account{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.UserDeposits[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testDepositsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Deposit{}
	if err = randomize.Struct(seed, o, depositDBTypes, true, depositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDepositsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Deposit{}
	if err = randomize.Struct(seed, o, depositDBTypes, true, depositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := DepositSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testDepositsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Deposit{}
	if err = randomize.Struct(seed, o, depositDBTypes, true, depositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Deposits().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	depositDBTypes = map[string]string{`ID`: `integer`, `Amount`: `bigint`, `TXHash`: `character varying`, `UserID`: `character varying`, `Date`: `bigint`}
	_              = bytes.MinRead
)

func testDepositsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(depositPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(depositAllColumns) == len(depositPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Deposit{}
	if err = randomize.Struct(seed, o, depositDBTypes, true, depositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Deposits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, depositDBTypes, true, depositPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testDepositsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(depositAllColumns) == len(depositPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Deposit{}
	if err = randomize.Struct(seed, o, depositDBTypes, true, depositColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Deposits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, depositDBTypes, true, depositPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(depositAllColumns, depositPrimaryKeyColumns) {
		fields = depositAllColumns
	} else {
		fields = strmangle.SetComplement(
			depositAllColumns,
			depositPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := DepositSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testDepositsUpsert(t *testing.T) {
	t.Parallel()

	if len(depositAllColumns) == len(depositPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Deposit{}
	if err = randomize.Struct(seed, &o, depositDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Deposit: %s", err)
	}

	count, err := Deposits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, depositDBTypes, false, depositPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Deposit struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Deposit: %s", err)
	}

	count, err = Deposits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
