// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testPromotionTasks(t *testing.T) {
	t.Parallel()

	query := PromotionTasks()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testPromotionTasksDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PromotionTask{}
	if err = randomize.Struct(seed, o, promotionTaskDBTypes, true, promotionTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PromotionTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPromotionTasksQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PromotionTask{}
	if err = randomize.Struct(seed, o, promotionTaskDBTypes, true, promotionTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := PromotionTasks().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PromotionTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPromotionTasksSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PromotionTask{}
	if err = randomize.Struct(seed, o, promotionTaskDBTypes, true, promotionTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PromotionTaskSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := PromotionTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testPromotionTasksExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PromotionTask{}
	if err = randomize.Struct(seed, o, promotionTaskDBTypes, true, promotionTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := PromotionTaskExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if PromotionTask exists: %s", err)
	}
	if !e {
		t.Errorf("Expected PromotionTaskExists to return true, but got false.")
	}
}

func testPromotionTasksFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PromotionTask{}
	if err = randomize.Struct(seed, o, promotionTaskDBTypes, true, promotionTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	promotionTaskFound, err := FindPromotionTask(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if promotionTaskFound == nil {
		t.Error("want a record, got nil")
	}
}

func testPromotionTasksBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PromotionTask{}
	if err = randomize.Struct(seed, o, promotionTaskDBTypes, true, promotionTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = PromotionTasks().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testPromotionTasksOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PromotionTask{}
	if err = randomize.Struct(seed, o, promotionTaskDBTypes, true, promotionTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := PromotionTasks().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testPromotionTasksAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	promotionTaskOne := &PromotionTask{}
	promotionTaskTwo := &PromotionTask{}
	if err = randomize.Struct(seed, promotionTaskOne, promotionTaskDBTypes, false, promotionTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}
	if err = randomize.Struct(seed, promotionTaskTwo, promotionTaskDBTypes, false, promotionTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = promotionTaskOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = promotionTaskTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := PromotionTasks().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testPromotionTasksCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	promotionTaskOne := &PromotionTask{}
	promotionTaskTwo := &PromotionTask{}
	if err = randomize.Struct(seed, promotionTaskOne, promotionTaskDBTypes, false, promotionTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}
	if err = randomize.Struct(seed, promotionTaskTwo, promotionTaskDBTypes, false, promotionTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = promotionTaskOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = promotionTaskTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PromotionTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testPromotionTasksInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PromotionTask{}
	if err = randomize.Struct(seed, o, promotionTaskDBTypes, true, promotionTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PromotionTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPromotionTasksInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PromotionTask{}
	if err = randomize.Struct(seed, o, promotionTaskDBTypes, true); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(promotionTaskColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := PromotionTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testPromotionTaskToOnePromotionUsingPromotion(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local PromotionTask
	var foreign Promotion

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, promotionTaskDBTypes, false, promotionTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, promotionDBTypes, false, promotionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Promotion struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.PromotionID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Promotion().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := PromotionTaskSlice{&local}
	if err = local.L.LoadPromotion(ctx, tx, false, (*[]*PromotionTask)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Promotion == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Promotion = nil
	if err = local.L.LoadPromotion(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Promotion == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testPromotionTaskToOneSetOpPromotionUsingPromotion(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a PromotionTask
	var b, c Promotion

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, promotionTaskDBTypes, false, strmangle.SetComplement(promotionTaskPrimaryKeyColumns, promotionTaskColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, promotionDBTypes, false, strmangle.SetComplement(promotionPrimaryKeyColumns, promotionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, promotionDBTypes, false, strmangle.SetComplement(promotionPrimaryKeyColumns, promotionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Promotion{&b, &c} {
		err = a.SetPromotion(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Promotion != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.PromotionTasks[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.PromotionID != x.ID {
			t.Error("foreign key was wrong value", a.PromotionID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.PromotionID))
		reflect.Indirect(reflect.ValueOf(&a.PromotionID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.PromotionID != x.ID {
			t.Error("foreign key was wrong value", a.PromotionID, x.ID)
		}
	}
}

func testPromotionTasksReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PromotionTask{}
	if err = randomize.Struct(seed, o, promotionTaskDBTypes, true, promotionTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPromotionTasksReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PromotionTask{}
	if err = randomize.Struct(seed, o, promotionTaskDBTypes, true, promotionTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := PromotionTaskSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testPromotionTasksSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &PromotionTask{}
	if err = randomize.Struct(seed, o, promotionTaskDBTypes, true, promotionTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := PromotionTasks().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	promotionTaskDBTypes = map[string]string{`ID`: `integer`, `PromotionID`: `integer`, `TaskType`: `character varying`, `TaskInfo`: `character varying`}
	_                    = bytes.MinRead
)

func testPromotionTasksUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(promotionTaskPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(promotionTaskAllColumns) == len(promotionTaskPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &PromotionTask{}
	if err = randomize.Struct(seed, o, promotionTaskDBTypes, true, promotionTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PromotionTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, promotionTaskDBTypes, true, promotionTaskPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testPromotionTasksSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(promotionTaskAllColumns) == len(promotionTaskPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &PromotionTask{}
	if err = randomize.Struct(seed, o, promotionTaskDBTypes, true, promotionTaskColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := PromotionTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, promotionTaskDBTypes, true, promotionTaskPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(promotionTaskAllColumns, promotionTaskPrimaryKeyColumns) {
		fields = promotionTaskAllColumns
	} else {
		fields = strmangle.SetComplement(
			promotionTaskAllColumns,
			promotionTaskPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := PromotionTaskSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testPromotionTasksUpsert(t *testing.T) {
	t.Parallel()

	if len(promotionTaskAllColumns) == len(promotionTaskPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := PromotionTask{}
	if err = randomize.Struct(seed, &o, promotionTaskDBTypes, true); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert PromotionTask: %s", err)
	}

	count, err := PromotionTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, promotionTaskDBTypes, false, promotionTaskPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize PromotionTask struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert PromotionTask: %s", err)
	}

	count, err = PromotionTasks().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
