// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Accounts", testAccountsUpsert)

	t.Run("Deposits", testDepositsUpsert)

	t.Run("Promotions", testPromotionsUpsert)

	t.Run("PromotionTasks", testPromotionTasksUpsert)

	t.Run("Rewards", testRewardsUpsert)

	t.Run("Withdrawals", testWithdrawalsUpsert)
}
