// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testRewards(t *testing.T) {
	t.Parallel()

	query := Rewards()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testRewardsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reward{}
	if err = randomize.Struct(seed, o, rewardDBTypes, true, rewardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Rewards().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRewardsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reward{}
	if err = randomize.Struct(seed, o, rewardDBTypes, true, rewardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Rewards().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Rewards().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRewardsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reward{}
	if err = randomize.Struct(seed, o, rewardDBTypes, true, rewardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RewardSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Rewards().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testRewardsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reward{}
	if err = randomize.Struct(seed, o, rewardDBTypes, true, rewardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := RewardExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Reward exists: %s", err)
	}
	if !e {
		t.Errorf("Expected RewardExists to return true, but got false.")
	}
}

func testRewardsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reward{}
	if err = randomize.Struct(seed, o, rewardDBTypes, true, rewardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	rewardFound, err := FindReward(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if rewardFound == nil {
		t.Error("want a record, got nil")
	}
}

func testRewardsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reward{}
	if err = randomize.Struct(seed, o, rewardDBTypes, true, rewardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Rewards().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testRewardsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reward{}
	if err = randomize.Struct(seed, o, rewardDBTypes, true, rewardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Rewards().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testRewardsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	rewardOne := &Reward{}
	rewardTwo := &Reward{}
	if err = randomize.Struct(seed, rewardOne, rewardDBTypes, false, rewardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}
	if err = randomize.Struct(seed, rewardTwo, rewardDBTypes, false, rewardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = rewardOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = rewardTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Rewards().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testRewardsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	rewardOne := &Reward{}
	rewardTwo := &Reward{}
	if err = randomize.Struct(seed, rewardOne, rewardDBTypes, false, rewardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}
	if err = randomize.Struct(seed, rewardTwo, rewardDBTypes, false, rewardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = rewardOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = rewardTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Rewards().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testRewardsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reward{}
	if err = randomize.Struct(seed, o, rewardDBTypes, true, rewardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Rewards().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRewardsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reward{}
	if err = randomize.Struct(seed, o, rewardDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(rewardColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := Rewards().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testRewardToOnePromotionUsingPromotion(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Reward
	var foreign Promotion

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, rewardDBTypes, false, rewardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, promotionDBTypes, false, promotionColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Promotion struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.PromotionID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Promotion().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := RewardSlice{&local}
	if err = local.L.LoadPromotion(ctx, tx, false, (*[]*Reward)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Promotion == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Promotion = nil
	if err = local.L.LoadPromotion(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Promotion == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testRewardToOneAccountUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Reward
	var foreign Account

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, rewardDBTypes, false, rewardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, accountDBTypes, false, accountColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Account struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := RewardSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*Reward)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}
}

func testRewardToOneSetOpPromotionUsingPromotion(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Reward
	var b, c Promotion

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, rewardDBTypes, false, strmangle.SetComplement(rewardPrimaryKeyColumns, rewardColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, promotionDBTypes, false, strmangle.SetComplement(promotionPrimaryKeyColumns, promotionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, promotionDBTypes, false, strmangle.SetComplement(promotionPrimaryKeyColumns, promotionColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Promotion{&b, &c} {
		err = a.SetPromotion(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Promotion != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Rewards[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.PromotionID != x.ID {
			t.Error("foreign key was wrong value", a.PromotionID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.PromotionID))
		reflect.Indirect(reflect.ValueOf(&a.PromotionID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.PromotionID != x.ID {
			t.Error("foreign key was wrong value", a.PromotionID, x.ID)
		}
	}
}
func testRewardToOneSetOpAccountUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Reward
	var b, c Account

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, rewardDBTypes, false, strmangle.SetComplement(rewardPrimaryKeyColumns, rewardColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, accountDBTypes, false, strmangle.SetComplement(accountPrimaryKeyColumns, accountColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, accountDBTypes, false, strmangle.SetComplement(accountPrimaryKeyColumns, accountColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Account{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.UserRewards[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testRewardsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reward{}
	if err = randomize.Struct(seed, o, rewardDBTypes, true, rewardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRewardsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reward{}
	if err = randomize.Struct(seed, o, rewardDBTypes, true, rewardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := RewardSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testRewardsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Reward{}
	if err = randomize.Struct(seed, o, rewardDBTypes, true, rewardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Rewards().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	rewardDBTypes = map[string]string{`ID`: `integer`, `UserID`: `character varying`, `PromotionID`: `integer`, `Date`: `bigint`, `Amount`: `bigint`}
	_             = bytes.MinRead
)

func testRewardsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(rewardPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(rewardAllColumns) == len(rewardPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Reward{}
	if err = randomize.Struct(seed, o, rewardDBTypes, true, rewardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Rewards().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, rewardDBTypes, true, rewardPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testRewardsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(rewardAllColumns) == len(rewardPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Reward{}
	if err = randomize.Struct(seed, o, rewardDBTypes, true, rewardColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Rewards().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, rewardDBTypes, true, rewardPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(rewardAllColumns, rewardPrimaryKeyColumns) {
		fields = rewardAllColumns
	} else {
		fields = strmangle.SetComplement(
			rewardAllColumns,
			rewardPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := RewardSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testRewardsUpsert(t *testing.T) {
	t.Parallel()

	if len(rewardAllColumns) == len(rewardPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Reward{}
	if err = randomize.Struct(seed, &o, rewardDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Reward: %s", err)
	}

	count, err := Rewards().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, rewardDBTypes, false, rewardPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Reward struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Reward: %s", err)
	}

	count, err = Rewards().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
