// Code generated by SQLBoiler 4.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Withdrawal is an object representing the database table.
type Withdrawal struct {
	ID     int    `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID string `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	Amount int64  `boil:"amount" json:"amount" toml:"amount" yaml:"amount"`
	TXHash string `boil:"tx_hash" json:"tx_hash" toml:"tx_hash" yaml:"tx_hash"`
	Date   int64  `boil:"date" json:"date" toml:"date" yaml:"date"`

	R *withdrawalR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L withdrawalL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WithdrawalColumns = struct {
	ID     string
	UserID string
	Amount string
	TXHash string
	Date   string
}{
	ID:     "id",
	UserID: "user_id",
	Amount: "amount",
	TXHash: "tx_hash",
	Date:   "date",
}

var WithdrawalTableColumns = struct {
	ID     string
	UserID string
	Amount string
	TXHash string
	Date   string
}{
	ID:     "withdrawal.id",
	UserID: "withdrawal.user_id",
	Amount: "withdrawal.amount",
	TXHash: "withdrawal.tx_hash",
	Date:   "withdrawal.date",
}

// Generated where

var WithdrawalWhere = struct {
	ID     whereHelperint
	UserID whereHelperstring
	Amount whereHelperint64
	TXHash whereHelperstring
	Date   whereHelperint64
}{
	ID:     whereHelperint{field: "\"withdrawal\".\"id\""},
	UserID: whereHelperstring{field: "\"withdrawal\".\"user_id\""},
	Amount: whereHelperint64{field: "\"withdrawal\".\"amount\""},
	TXHash: whereHelperstring{field: "\"withdrawal\".\"tx_hash\""},
	Date:   whereHelperint64{field: "\"withdrawal\".\"date\""},
}

// WithdrawalRels is where relationship names are stored.
var WithdrawalRels = struct {
	User string
}{
	User: "User",
}

// withdrawalR is where relationships are stored.
type withdrawalR struct {
	User *Account `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*withdrawalR) NewStruct() *withdrawalR {
	return &withdrawalR{}
}

// withdrawalL is where Load methods for each relationship are stored.
type withdrawalL struct{}

var (
	withdrawalAllColumns            = []string{"id", "user_id", "amount", "tx_hash", "date"}
	withdrawalColumnsWithoutDefault = []string{"user_id", "amount", "tx_hash", "date"}
	withdrawalColumnsWithDefault    = []string{"id"}
	withdrawalPrimaryKeyColumns     = []string{"id"}
)

type (
	// WithdrawalSlice is an alias for a slice of pointers to Withdrawal.
	// This should almost always be used instead of []Withdrawal.
	WithdrawalSlice []*Withdrawal

	withdrawalQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	withdrawalType                 = reflect.TypeOf(&Withdrawal{})
	withdrawalMapping              = queries.MakeStructMapping(withdrawalType)
	withdrawalPrimaryKeyMapping, _ = queries.BindMapping(withdrawalType, withdrawalMapping, withdrawalPrimaryKeyColumns)
	withdrawalInsertCacheMut       sync.RWMutex
	withdrawalInsertCache          = make(map[string]insertCache)
	withdrawalUpdateCacheMut       sync.RWMutex
	withdrawalUpdateCache          = make(map[string]updateCache)
	withdrawalUpsertCacheMut       sync.RWMutex
	withdrawalUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single withdrawal record from the query.
func (q withdrawalQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Withdrawal, error) {
	o := &Withdrawal{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for withdrawal")
	}

	return o, nil
}

// All returns all Withdrawal records from the query.
func (q withdrawalQuery) All(ctx context.Context, exec boil.ContextExecutor) (WithdrawalSlice, error) {
	var o []*Withdrawal

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Withdrawal slice")
	}

	return o, nil
}

// Count returns the count of all Withdrawal records in the query.
func (q withdrawalQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count withdrawal rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q withdrawalQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if withdrawal exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *Withdrawal) User(mods ...qm.QueryMod) accountQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	query := Accounts(queryMods...)
	queries.SetFrom(query.Query, "\"account\"")

	return query
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (withdrawalL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWithdrawal interface{}, mods queries.Applicator) error {
	var slice []*Withdrawal
	var object *Withdrawal

	if singular {
		object = maybeWithdrawal.(*Withdrawal)
	} else {
		slice = *maybeWithdrawal.(*[]*Withdrawal)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &withdrawalR{}
		}
		args = append(args, object.UserID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &withdrawalR{}
			}

			for _, a := range args {
				if a == obj.UserID {
					continue Outer
				}
			}

			args = append(args, obj.UserID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`account`),
		qm.WhereIn(`account.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Account")
	}

	var resultSlice []*Account
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Account")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for account")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for account")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &accountR{}
		}
		foreign.R.UserWithdrawals = append(foreign.R.UserWithdrawals, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &accountR{}
				}
				foreign.R.UserWithdrawals = append(foreign.R.UserWithdrawals, local)
				break
			}
		}
	}

	return nil
}

// SetUser of the withdrawal to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserWithdrawals.
func (o *Withdrawal) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Account) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"withdrawal\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, withdrawalPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &withdrawalR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &accountR{
			UserWithdrawals: WithdrawalSlice{o},
		}
	} else {
		related.R.UserWithdrawals = append(related.R.UserWithdrawals, o)
	}

	return nil
}

// Withdrawals retrieves all the records using an executor.
func Withdrawals(mods ...qm.QueryMod) withdrawalQuery {
	mods = append(mods, qm.From("\"withdrawal\""))
	return withdrawalQuery{NewQuery(mods...)}
}

// FindWithdrawal retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWithdrawal(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*Withdrawal, error) {
	withdrawalObj := &Withdrawal{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"withdrawal\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, withdrawalObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from withdrawal")
	}

	return withdrawalObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Withdrawal) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no withdrawal provided for insertion")
	}

	var err error

	nzDefaults := queries.NonZeroDefaultSet(withdrawalColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	withdrawalInsertCacheMut.RLock()
	cache, cached := withdrawalInsertCache[key]
	withdrawalInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			withdrawalAllColumns,
			withdrawalColumnsWithDefault,
			withdrawalColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(withdrawalType, withdrawalMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(withdrawalType, withdrawalMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"withdrawal\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"withdrawal\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into withdrawal")
	}

	if !cached {
		withdrawalInsertCacheMut.Lock()
		withdrawalInsertCache[key] = cache
		withdrawalInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Withdrawal.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Withdrawal) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	withdrawalUpdateCacheMut.RLock()
	cache, cached := withdrawalUpdateCache[key]
	withdrawalUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			withdrawalAllColumns,
			withdrawalPrimaryKeyColumns,
		)

		if len(wl) == 0 {
			return 0, errors.New("models: unable to update withdrawal, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"withdrawal\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, withdrawalPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(withdrawalType, withdrawalMapping, append(wl, withdrawalPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update withdrawal row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for withdrawal")
	}

	if !cached {
		withdrawalUpdateCacheMut.Lock()
		withdrawalUpdateCache[key] = cache
		withdrawalUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q withdrawalQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for withdrawal")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for withdrawal")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WithdrawalSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), withdrawalPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"withdrawal\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, withdrawalPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in withdrawal slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all withdrawal")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Withdrawal) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no withdrawal provided for upsert")
	}

	nzDefaults := queries.NonZeroDefaultSet(withdrawalColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	withdrawalUpsertCacheMut.RLock()
	cache, cached := withdrawalUpsertCache[key]
	withdrawalUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			withdrawalAllColumns,
			withdrawalColumnsWithDefault,
			withdrawalColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			withdrawalAllColumns,
			withdrawalPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert withdrawal, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(withdrawalPrimaryKeyColumns))
			copy(conflict, withdrawalPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"withdrawal\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(withdrawalType, withdrawalMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(withdrawalType, withdrawalMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert withdrawal")
	}

	if !cached {
		withdrawalUpsertCacheMut.Lock()
		withdrawalUpsertCache[key] = cache
		withdrawalUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Withdrawal record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Withdrawal) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Withdrawal provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), withdrawalPrimaryKeyMapping)
	sql := "DELETE FROM \"withdrawal\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from withdrawal")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for withdrawal")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q withdrawalQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no withdrawalQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from withdrawal")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for withdrawal")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WithdrawalSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), withdrawalPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"withdrawal\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, withdrawalPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from withdrawal slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for withdrawal")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Withdrawal) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWithdrawal(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WithdrawalSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WithdrawalSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), withdrawalPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"withdrawal\".* FROM \"withdrawal\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, withdrawalPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in WithdrawalSlice")
	}

	*o = slice

	return nil
}

// WithdrawalExists checks if the Withdrawal row exists.
func WithdrawalExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"withdrawal\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if withdrawal exists")
	}

	return exists, nil
}
